
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Windows 18
 */
public class DeparmentManager extends javax.swing.JFrame {

    String dataPath = "a.txt";
    private boolean addDepMode = false;
    private boolean addEmpMode = false;

    DefaultMutableTreeNode curDepNode = null;
    DefaultMutableTreeNode curEmpNode = null;

    private DefaultMutableTreeNode root;

    public DeparmentManager() {

        initComponents();
        root = (DefaultMutableTreeNode) this.depTree.getModel().getRoot();

        initDepTree();
        this.depTree.expandPath(new TreePath(root));
        this.setLocationRelativeTo(null);

    }

    private void initDepTree() {
        String depRegex = "^(\\w+)-(.+):(.*)$";//G1 code , G2 Name
        String empRegex = "^(\\w+),(.+),(\\d+)(.*)$";//G1 Code, G2 Name, G3 Salary
        DefaultMutableTreeNode currentDepNode = null;
        try {
//            JFileChooser f  = new JFileChooser();
//            f.showOpenDialog(this);
            BufferedReader reader = new BufferedReader(new FileReader(new File(dataPath)));
            while (reader.ready()) {
                String line = reader.readLine();

                //is Department
                if (line.matches(depRegex)) {
                    System.out.println(line);
                    Pattern depPattern = Pattern.compile(depRegex);
                    Matcher depMatcher = depPattern.matcher(line);
                    //WARNING:
                    //De su dung duoc cac ham group thi can phai co ham matches de thong bao cho mathcer
                    if (depMatcher.matches()) {
                        System.out.println(depMatcher.group(1) + " " + depMatcher.group(2));
                        DefaultMutableTreeNode depNode = new DefaultMutableTreeNode(new Department(depMatcher.group(1), depMatcher.group(2)));
                        currentDepNode = depNode;
                        root.add(depNode);
                    }

                } else if (line.matches(empRegex)) {//is Employee
                    Pattern empPattern = Pattern.compile(empRegex);
                    Matcher empMatcher = empPattern.matcher(line);
                    if (empMatcher.matches()) {
                        DefaultMutableTreeNode empNode = new DefaultMutableTreeNode(new Employee(empMatcher.group(1), empMatcher.group(2), Integer.parseInt(empMatcher.group(3))));
                        currentDepNode.add(empNode);
                    }
                }
            }
            reader.close();

        } catch (Exception ex) {
            Logger.getLogger(DeparmentManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        depTree = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDepCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDepName = new javax.swing.JTextField();
        saveDepBtn = new javax.swing.JLabel();
        removeDepBtn = new javax.swing.JLabel();
        newDepBtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        saveEmpBtn = new javax.swing.JLabel();
        removeEmpBtn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmpSalary = new javax.swing.JTextField();
        newEmpBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        depTree.setBackground(new java.awt.Color(102, 102, 102));
        depTree.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Department");
        depTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        depTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(depTree);

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Save to File");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dept. Code:");

        txtDepCode.setEditable(false);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dept. Name:");

        txtDepName.setEditable(false);

        saveDepBtn.setBackground(new java.awt.Color(153, 153, 153));
        saveDepBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveDepBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveDepBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveDepBtn.setText("Save");
        saveDepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveDepBtn.setOpaque(true);
        saveDepBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveDepBtnMouseClicked(evt);
            }
        });

        removeDepBtn.setBackground(new java.awt.Color(153, 153, 153));
        removeDepBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeDepBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeDepBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeDepBtn.setText("Remove");
        removeDepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeDepBtn.setOpaque(true);
        removeDepBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeDepBtnMouseClicked(evt);
            }
        });

        newDepBtn.setBackground(new java.awt.Color(153, 153, 153));
        newDepBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newDepBtn.setForeground(new java.awt.Color(255, 255, 255));
        newDepBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newDepBtn.setText("New");
        newDepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newDepBtn.setOpaque(true);
        newDepBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newDepBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtDepCode, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(newDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(removeDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Emp. Code:");

        txtEmpCode.setEditable(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Emp. Name:");

        txtEmpName.setEditable(false);

        saveEmpBtn.setBackground(new java.awt.Color(153, 153, 153));
        saveEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveEmpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveEmpBtn.setText("Save");
        saveEmpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveEmpBtn.setOpaque(true);
        saveEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveEmpBtnMouseClicked(evt);
            }
        });

        removeEmpBtn.setBackground(new java.awt.Color(153, 153, 153));
        removeEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeEmpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeEmpBtn.setText("Remove");
        removeEmpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeEmpBtn.setOpaque(true);
        removeEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeEmpBtnMouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Salary");

        txtEmpSalary.setEditable(false);

        newEmpBtn.setBackground(new java.awt.Color(153, 153, 153));
        newEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        newEmpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newEmpBtn.setText("New");
        newEmpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newEmpBtn.setOpaque(true);
        newEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newEmpBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtEmpCode, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtEmpName))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(newEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(removeEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateContentInfo() {

        txtDepCode.setText(curDepNode != null ? ((Department) curDepNode.getUserObject()).getDepCode() : "");
        txtDepName.setText(curDepNode != null ? ((Department) curDepNode.getUserObject()).getDepName() : "");

        txtDepCode.setEditable(addDepMode);
        txtDepName.setEditable(addDepMode);
        
        
        txtEmpCode.setText(curEmpNode != null ? ((Employee) curEmpNode.getUserObject()).getEmpCode() : "");
        txtEmpName.setText(curEmpNode != null ? ((Employee) curEmpNode.getUserObject()).getEmpName() : "");
        txtEmpSalary.setText(curEmpNode != null ? Integer.toString(((Employee) curEmpNode.getUserObject()).getSalary()) : "");

        txtEmpCode.setEditable(addEmpMode);
        txtEmpName.setEditable(addEmpMode);
        txtEmpSalary.setEditable(addEmpMode);
        
    }

    private void depTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depTreeMouseClicked
        // TODO add your handling code here:

        TreePath selectionPath = this.depTree.getSelectionPath();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
        if (selectionPath == null || selectedNode == root) {
            return;
        }
        //turn off save btn
        addDepMode = false;
        addEmpMode = false;
        txtDepCode.setEditable(true);
            txtDepName.setEditable(true);
            txtEmpCode.setEditable(true);
            txtEmpName.setEditable(true);
            txtEmpSalary.setEditable(true);
        //TH selected node la depNode
            
        if (selectedNode.getUserObject() instanceof Department) {

            curDepNode = selectedNode;
            curEmpNode = null;
            updateContentInfo();

        } else {
            curEmpNode = selectedNode;
            updateContentInfo();
        }

    }//GEN-LAST:event_depTreeMouseClicked

    private void newDepBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDepBtnMouseClicked
        // TODO add your handling code here:
        curDepNode = null;
        addDepMode = true;
        txtDepCode.setText("");
        txtDepName.setText("");
        txtDepCode.setEditable(true);
        txtDepName.setEditable(true);
        txtDepCode.requestFocus();
        
    }//GEN-LAST:event_newDepBtnMouseClicked

    private void newEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmpBtnMouseClicked
        // TODO add your handling code here:
        curEmpNode = null;
        addEmpMode = true;
        txtEmpCode.setText("");
        txtEmpName.setText("");
        txtEmpSalary.setText("");
        txtEmpCode.setEditable(true);
        txtEmpName.setEditable(true);
        txtEmpSalary.setEditable(true);
        
        
    }//GEN-LAST:event_newEmpBtnMouseClicked

    private boolean isValidDepInput(){
        return txtDepCode.getText().trim().length() > 0 && txtDepName.getText().trim().length() > 0;
    }
    
    private boolean isValidEmpInput(){
        
        String salary = txtEmpSalary.getText();
        return txtEmpCode.getText().trim().length() > 0 && txtEmpName.getText().trim().length() > 0 && salary.matches("^\\d+$");
    }
    
    
    private void saveDepBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDepBtnMouseClicked
        // TODO add your handling code here:
        if(!isValidDepInput())
            JOptionPane.showMessageDialog(this, "Not valid input");
        else{
            if(addDepMode){//save new
                DefaultMutableTreeNode newDepNode = new DefaultMutableTreeNode(new Department(txtDepCode.getText(), txtDepName.getText()));
                root.add(newDepNode);
            }else{
                Department curDepartment = (Department) curDepNode.getUserObject();
                curDepartment.setDepCode(txtDepCode.getText());
                curDepartment.setDepName(txtDepName.getText());
            }
            this.depTree.updateUI();
            addDepMode = false;
            curDepNode = null;
        }
    }//GEN-LAST:event_saveDepBtnMouseClicked

    private void saveEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveEmpBtnMouseClicked
        // TODO add your handling code here:
        
        if(curDepNode == null){
            JOptionPane.showMessageDialog(this, "Please choose deapartment");
            return;
        }
        if(!isValidEmpInput())
            JOptionPane.showMessageDialog(this, "Not valid input");
        else{
            if(addEmpMode){
                DefaultMutableTreeNode newEmpNode = new DefaultMutableTreeNode(new Employee(txtEmpCode.getText(), txtEmpName.getText(),Integer.parseInt(txtEmpSalary.getText())));
                curDepNode.add(newEmpNode);
            }else{
                Employee curEmployee = (Employee) curEmpNode.getUserObject();
                curEmployee.setEmpCode(txtEmpCode.getText());
                curEmployee.setEmpName(txtEmpName.getText());
                curEmployee.setSalary(Integer.parseInt(txtEmpSalary.getText()));
            }
            
            this.depTree.updateUI();
            addEmpMode = false;
        }
        
        
    }//GEN-LAST:event_saveEmpBtnMouseClicked

    private void removeDepBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeDepBtnMouseClicked
        // TODO add your handling code here:
        if(curDepNode == null)
            return;
        if(curDepNode.getChildCount() > 0)
            JOptionPane.showMessageDialog(this, "Remove all employee before deleting a department");
        else{
            
            int response = JOptionPane.showConfirmDialog(this, "Do you want to delete this department");
            if(response == JOptionPane.OK_OPTION){
                this.root.remove(curDepNode);
                this.depTree.updateUI();
                updateContentInfo();
                curDepNode= curEmpNode = null ;
            }
        }
        
    }//GEN-LAST:event_removeDepBtnMouseClicked

    private void removeEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEmpBtnMouseClicked
        // TODO add your handling code here:
        if(curEmpNode == null)
            return;
        int response = JOptionPane.showConfirmDialog(this, "Do you want to delete this Employee");
            if(response == JOptionPane.OK_OPTION){
                curDepNode.remove(curEmpNode);
                curEmpNode = null;
                depTree.updateUI();
                updateContentInfo();
            }
        
    }//GEN-LAST:event_removeEmpBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeparmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeparmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeparmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeparmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeparmentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree depTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newDepBtn;
    private javax.swing.JLabel newEmpBtn;
    private javax.swing.JLabel removeDepBtn;
    private javax.swing.JLabel removeEmpBtn;
    private javax.swing.JLabel saveDepBtn;
    private javax.swing.JLabel saveEmpBtn;
    private javax.swing.JTextField txtDepCode;
    private javax.swing.JTextField txtDepName;
    private javax.swing.JTextField txtEmpCode;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpSalary;
    // End of variables declaration//GEN-END:variables
}
